
title: "Luis Iván — Research & Projects"
description: "Research blog, models, courses, and more."
url: "https://luisivanhr.github.io"  # set to your custom domain (e.g., https://luisivanhr.com)
baseurl: ""

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
paginate: 10
paginate_path: "/blog/page:num/"

collections:
  models:
    output: true
    permalink: /models/:title/
  courses:
    output: true
    permalink: /courses/:title/
  hobbies:
    output: true
    permalink: /hobbies/:title/
  achievements:
    output: true
    permalink: /achievements/:title/
  news:
    output: true
    permalink: /news/:title/
  publications:
    output: true
    permalink: /publications/:title/
  blog:
    output: true
    permalink: /blog/:title/

  defaults:
  - scope:
      path: ""
    values:
      layout: default
      image: /assets/images/og-default.png
  - scope:
      path: "data"
    values:
      layout: null


markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# Build JSON feeds to /data
permalink: pretty
