
title: "Luis Iván — Research & Projects"
description: "Research blog, models, courses, and more."
url: "https://luisivanhr.github.io"  # set to your custom domain (e.g., https://luisivanhr.com)
baseurl: ""

disqus_shortname: luisivanhr

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  about:
    output: true
    permalink: /about/:title/
  models:
    output: true
    permalink: /models/:title/
  courses:
    output: true
    permalink: /courses/:title/
  course_sections:
    output: true
    permalink: /courses/:path/
  hobbies:
    output: true
    permalink: /hobbies/:title/
  achievements:
    output: true
    permalink: /achievements/:title/
  news:
    output: true
    permalink: /news/:title/
  publications:
    output: true
    permalink: /publications/:title/

defaults:
  - scope: {path: ""}
    values:
      layout: default
      image: /assets/images/og-default.png
  - scope: {path: "", type: "courses"}
    values:
      layout: course
  - scope: {path: "", type: "models"}
    values:
      layout: model
  - scope: {path: "", type: "course_sections"}
    values:
      layout: course-section
      course_section_style: theory

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# Build JSON feeds to /data
permalink: pretty
